name: filterable_logger
description: A logger with color output and filters.
version: 0.0.7
homepage:
repository: https://github.com/dddrop/filterable_logger

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  logging: '>=1.0.0 <2.0.0'
  stack_trace: '>=1.0.0 <2.0.0'

dev_dependencies:
  flutter_lints: '>=1.0.0 <2.0.0'
  test: '>=1.0.0 <2.0.0'